# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: ABR Dynamic Funds - Python - CI

on:
  push:
    # main = default top-level branch name, master = deprecated name
    # run CI on every branch push except top-level
    branches:
      - '*'
      - '!master'
      - '!main'
  pull_request:
    branches:
      - 'master'
      - 'main'
  # allow running workflow manually
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    # runs-on: windows-latest # uncomment to run on Windows instead

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        # pulls latest version of python, alternatively specify exact version (i.e. 3.8 -> no quotes)
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel
        pip install flake8 pytest
        pip install -r requirements.txt
        pip install git+https://adamiani:${{ secrets.GH_ACCESS_TOKEN }}@github.com/adamiani-abr/email_helpers.git
        # pip install git+https://adamiani:${{ secrets.GH_ACCESS_TOKEN }}@github.com/adamiani-abr/ftp_workflows.git
    - name: Lint with flake8
      run: |
        # fail if there are any flake8 errors
        flake8 . --count --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        python -m pytest

